### ISSUE TITLE
Improve saving user data on memory

### ISSUE THREAD

**Issue by diCaminha** [gladguys/acta#68]
in the SignIn Screen Bloc, the method storeUserInfo would be more efficient if check first if it really need to save the data with sharedpreference. Because the data might already be there, so it's better check first if there isnt data yet, and then save it.

for the token, just check the expiration, and save if it.

**Comment by rodrigobastosv** [comment]
I guess this is not a big deal. This method is executed only once on the login. Most of the time the user will be autologged so i guess this is not a big deal. What's your thoughts @diCaminha ?
